const movies = [
  // Bollywood Movies
  {
    id: 1,
    name: "Dilwale Dulhania Le Jayenge",
    genre: ["Romance", "Drama"],
    director: "Aditya Chopra",
    year: 1995,
    rating: 9.1,
    actors: ["Shah Rukh Khan", "Kajol"],
    actresses: ["Amrish Puri", "Farida Jalal"],
  },
  {
    id: 2,
    name: "Lagaan",
    genre: ["Drama", "Sport"],
    director: "Ashutosh Gowariker",
    year: 2001,
    rating: 8.1,
    actors: ["Aamir Khan", "Gracy Singh"],
    actresses: ["Rachel Shelley", "Paul Blackthorne"],
  },
  {
    id: 3,
    name: "3 Idiots",
    genre: ["Comedy", "Drama"],
    director: "Rajkumar Hirani",
    year: 2009,
    rating: 8.4,
    actors: ["Aamir Khan", "Kareena Kapoor"],
    actresses: ["R. Madhavan", "Sharman Joshi"],
  },
  {
    id: 4,
    name: "Queen",
    genre: ["Drama", "Comedy"],
    director: "Vikas Bahl",
    year: 2013,
    rating: 8.2,
    actors: ["Kangana Ranaut"],
    actresses: [],
  },
  {
    id: 5,
    name: "Dangal",
    genre: ["Biography", "Sport"],
    director: "Nitesh Tiwari",
    year: 2016,
    rating: 8.4,
    actors: ["Aamir Khan", "Fatima Sana Shaikh"],
    actresses: ["Sakshi Tanwar"],
  },
  {
    id: 6,
    name: "Andaz Apna Apna",
    genre: ["Comedy", "Romance"],
    director: "Rajkumar Santoshi",
    year: 1994,
    rating: 8.2,
    actors: ["Aamir Khan", "Salman Khan"],
    actresses: ["Raveena Tandon", "Karisma Kapoor"],
  },
  {
    id: 7,
    name: "Sholay",
    genre: ["Action", "Adventure"],
    director: "Ramesh Sippy",
    year: 1975,
    rating: 8.2,
    actors: ["Dharmendra", "Amitabh Bachchan"],
    actresses: ["Hema Malini", "Jaya Bachchan"],
  },
  {
    id: 8,
    name: "PK",
    genre: ["Comedy", "Drama"],
    director: "Rajkumar Hirani",
    year: 2014,
    rating: 8.1,
    actors: ["Aamir Khan", "Anushka Sharma"],
    actresses: ["Sushant Singh Rajput"],
  },
  {
    id: 9,
    name: "Gully Boy",
    genre: ["Drama", "Music"],
    director: "Zoya Akhtar",
    year: 2019,
    rating: 8.1,
    actors: ["Ranveer Singh", "Alia Bhatt"],
    actresses: ["Kalki Koechlin"],
  },
  {
    id: 10,
    name: "Barfi!",
    genre: ["Comedy", "Drama"],
    director: "Anurag Basu",
    year: 2012,
    rating: 8.1,
    actors: ["Ranbir Kapoor", "Priyanka Chopra"],
    actresses: ["Ileana D'Cruz"],
  },
  // Hollywood Movies
  {
    id: 11,
    name: "The Shawshank Redemption",
    genre: ["Drama"],
    director: "Frank Darabont",
    year: 1994,
    rating: 9.3,
    actors: ["Tim Robbins", "Morgan Freeman"],
    actresses: [],
  },
  {
    id: 12,
    name: "The Godfather",
    genre: ["Crime", "Drama"],
    director: "Francis Ford Coppola",
    year: 1972,
    rating: 9.2,
    actors: ["Marlon Brando", "Al Pacino"],
    actresses: ["Diane Keaton"],
  },
  {
    id: 13,
    name: "The Dark Knight",
    genre: ["Action", "Crime", "Drama"],
    director: "Christopher Nolan",
    year: 2008,
    rating: 9.0,
    actors: ["Christian Bale", "Heath Ledger"],
    actresses: ["Maggie Gyllenhaal", "Anne Hathaway"],
  },
  {
    id: 14,
    name: "The Lord of the Rings: The Return of the King",
    genre: ["Adventure", "Drama", "Fantasy"],
    director: "Peter Jackson",
    year: 2003,
    rating: 8.9,
    actors: ["Elijah Wood", "Viggo Mortensen"],
    actresses: ["Liv Tyler", "Cate Blanchett"],
  },
  {
    id: 15,
    name: "Forrest Gump",
    genre: ["Drama", "Romance"],
    director: "Robert Zemeckis",
    year: 1994,
    rating: 8.8,
    actors: ["Tom Hanks", "Robin Wright"],
    actresses: ["Sally Field"],
  },
  {
    id: 16,
    name: "Inception",
    genre: ["Action", "Adventure", "Sci-Fi"],
    director: "Christopher Nolan",
    year: 2010,
    rating: 8.8,
    actors: ["Leonardo DiCaprio", "Joseph Gordon-Levitt"],
    actresses: ["Ellen Page", "Marion Cotillard"],
  },
  {
    id: 17,
    name: "Fight Club",
    genre: ["Drama"],
    director: "David Fincher",
    year: 1999,
    rating: 8.8,
    actors: ["Brad Pitt", "Edward Norton"],
    actresses: ["Helena Bonham Carter"],
  },
  {
    id: 18,
    name: "The Matrix",
    genre: ["Action", "Sci-Fi"],
    director: "Lana Wachowski",
    year: 1999,
    rating: 8.7,
    actors: ["Keanu Reeves", "Laurence Fishburne"],
    actresses: ["Carrie-Anne Moss"],
  },
  {
    id: 19,
    name: "Goodfellas",
    genre: ["Biography", "Crime", "Drama"],
    director: "Martin Scorsese",
    year: 1990,
    rating: 8.7,
    actors: ["Robert De Niro", "Ray Liotta"],
    actresses: ["Lorraine Bracco"],
  },
  {
    id: 20,
    name: "Pulp Fiction",
    genre: ["Crime", "Drama"],
    director: "Quentin Tarantino",
    year: 1994,
    rating: 8.9,
    actors: ["John Travolta", "Uma Thurman"],
    actresses: ["Samuel L. Jackson", "Bruce Willis"],
  },
  // Continue adding more movies here...
];



module.exports = movies;
