const users = [
    {
      id: 1,
      name: "User A",
      preferences: {
        movies: {
          1: 4,
          2: 0  ,
          3: 0,
          4: 0,
          5: 0,
          6: 0,
          7: 0,
          8: 0,
          9: 0,
          10: 5,
        },
        restaurants: {
          1: 0,
          2: 0,
          3: 0,
          4: 0,
          5: 0,
          6: 5,
          7: 0,
          8: 0,
          9: 0,
          10: 0,
          11: 0,
          12: 8,
        },
      },
    },
    {
      id: 2,
      name: "User B",
      preferences: {
        movies: {
          1: 5,
          2: 0,
          3: 0,
          4: 4,
          5: 3,
          6: 5,
          7: 0,
          8: 0,
          9: 0,
          10: 0,
        },
        restaurants: {
          1: 0,
          2: 0,
          3: 4,
          4: 0,
          5: 0,
          6: 0,
          7: 3,
          8: 5,
          9: 4,
          10: 0,
          11: 0,
          12: 0,
        },
      },
    },
    {
      id: 3,
      name: "User C",
      preferences: {
        movies: {
          1: 0,  // Rating for Dilwale Dulhania Le Jayenge
          2: 3,  // Rating for Lagaan
          3: 0,
          4: 0,
          5: 0,
          6: 0,
          7: 4,
          8: 3,
          9: 5,
          10: 0,
        },
        restaurants: {
          1: 0,
          2: 0,
          3: 0,
          4: 0,
          5: 0,
          6: 8,
          7: 0,
          8: 0,
          9: 0,
          10: 0,
          11: 0,
          12: 0,
        },
      },
    },
  ];
  
  module.exports = users;
  